#ifndef YAMSERVICEENGINE_GLOBAL_H
#define YAMSERVICEENGINE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(YAMSERVICEENGINE_LIBRARY)
#  define YAMSERVICEENGINESHARED_EXPORT Q_DECL_EXPORT
#else
#  define YAMSERVICEENGINESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // YAMSERVICEENGINE_GLOBAL_H
